export const GET_COUNTRIES = 'GET_COUNTRIES';
export const FILTER_BY_CONTINENTS = 'FILTER_BY_CONTINENTS';
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const ORDER_BY_POPULATION = 'ORDER_BY_POPULATION';
export const GET_NAME_COUNTRIES = 'GET_NAME_COUNTRIES';