export const GET_COUNTRIES = 'GET_COUNTRIES';
export const FILTER_BY_CONTINENTS = 'FILTER_BY_CONTINENTS';
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const ORDER_BY_POPULATION = 'ORDER_BY_POPULATION';
export const GET_NAME_COUNTRIES = 'GET_NAME_COUNTRIES';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const POST_ACTIVITY = 'POST_ACTIVITY';
export const GET_COUNTRY_ID = 'GET_COUNTRY_ID';